apiVersion: v1
kind: Service
metadata:
  name: products
spec:
  type: {{ .Values.products.service.type }}
  selector:
    app: products
  ports:
    - port: {{ .Values.products.service.port }}
      targetPort: {{ .Values.products.service.targetPort }}
